### ISSUE TITLE
JAVA_HOME Jython and Sleuthkit errors

### ISSUE THREAD

**Issue by stressatoo** [sathwikv143/Autopsy-Whatsapp-Plugin#1]
Hi, I searched for entire months something like your project, now I found it but it is not working cause Jython and Sleuthkit are not working (Jython provides a JAVA_HOME error)

Could you provide a requirements.txt?
I would really like your help for that.

 
Much appreciated in advance,
Alessandro.

**Comment by stressatoo** [comment]
sorry, I meant Jython -- wrote "Cython" on the email.

**Comment by stressatoo** [comment]
bump

**Comment by stressatoo** [comment]
bump

**Comment by sathwikv143** [comment]
Hello @stressatoo 
Sorry for being late!
There is no need for `requirement.txt` as all the required modules which are default will be available in Autopsy's python environment.
